README.md
logion-network/logion-internal#159
=> chore: refer to new typescript backend.

additional-types.json, pallets/logion_loc/src/benchmarking.rs, pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/mock.rs, pallets/logion_loc/src/tests.rs, pallets/logion_loc/src/weights.rs
logion-network/logion-internal#186
=> feat: add LOC metadata.

additional-types.json, pallets/logion_loc/src/benchmarking.rs, pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/mock.rs, pallets/logion_loc/src/tests.rs, pallets/logion_loc/src/weights.rs, runtime/src/lib.rs
logion-network/logion-node#189
=> feat: add hashes to LOC.

pallets/logion_loc/src/benchmarking.rs, pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/tests.rs, pallets/logion_loc/src/weights.rs
logion-network/logion-node#193
=> feat: implement LOC close.

additional-types.json, pallets/logion_loc/src/benchmarking.rs, pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/tests.rs, pallets/logion_loc/src/weights.rs
logion-network/logion-internal#224
=> feat: add file nature; make loc links explicit.

Dockerfile
logion-network/logion-internal#236
=> feat: move safety options to custom.

pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/migration.rs
logion-network/logion-internal#266
=> fix: palletStorageVersion when chain booted from a newer version.

docs/storage_backward_compatibility.md
logion-network/logion-internal#266
=> feat: document migration.

pallets/logion_loc/src/tests.rs
logion-network/logion-internal#266
=> feat: add error cases tests.

additional-types.json, pallets/logion_loc/src/benchmarking.rs, pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/migration.rs, pallets/logion_loc/src/mock.rs, pallets/logion_loc/src/tests.rs, pallets/logion_loc/src/weights.rs, runtime/src/lib.rs, scripts/local_run.sh
logion-network/logion-internal#297
=> feat: make requester an enum.

additional-types.json, pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/migration.rs
logion-network/logion-internal#312
=> feat: API update for file/metadata submitter .

pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/tests.rs
logion-network/logion-internal#312
logion-network/logion-internal#317
=> feat: prevent replacing loc with different type loc.

pallets/logion_loc/src/migration.rs, runtime/src/lib.rs
logion-network/logion-internal#313
=> feat: implement migration.

pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/tests.rs
logion-network/logion-internal#313
=> feat: implement submitter validation.

additional-types.json, pallets/logion_loc/src/benchmarking.rs, pallets/logion_loc/src/lib.rs, pallets/logion_loc/src/migration.rs, pallets/logion_loc/src/mock.rs, pallets/logion_loc/src/tests.rs, pallets/logion_loc/src/weights.rs, runtime/src/lib.rs
logion-network/logion-internal#353
=> feat: add collections.

Cargo.lock, pallets/lo_authority_list/src/lib.rs, pallets/lo_authority_list/src/tests.rs, pallets/shared/src/lib.rs, pallets/vault/Cargo.toml, pallets/vault/src/lib.rs, pallets/vault/src/mock.rs, pallets/vault/src/tests.rs, runtime/Cargo.toml, runtime/src/lib.rs
logion-network/logion-internal#398
=> feat: implement vault.

Cargo.lock, node/Cargo.toml, node/src/rpc.rs, runtime/Cargo.toml, runtime/src/lib.rs
logion-network/logion-internal#540
=> feat: enable item tokens

Cargo.lock, node/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
logion-network/logion-internal#557
=> chore: upgrade to polkadot-v0.9.26.

Cargo.lock, runtime/Cargo.toml, runtime/src/lib.rs
logion-network/logion-internal#587
=> Upgrade pallet logion-loc (Terms and Conditions).

.github/workflows/rust.yml, Cargo.lock, node/Cargo.toml, node/src/benchmarking.rs, node/src/command.rs, node/src/service.rs, runtime/Cargo.toml, runtime/src/lib.rs
logion-network/logion-internal#630
=> Upgrade to polkadot-v0.9.30

Cargo.lock, node/Cargo.toml, node/src/cli.rs, runtime/Cargo.toml, runtime/src/lib.rs
* One migration queued (multisig pallet)
* Re-aligned with node template
logion-network/logion-internal#656
=> Upgrade to polkadot-v0.9.31

Cargo.lock, runtime/src/lib.rs
The node upgrade for this PR: https://github.com/logion-network/logion-pallets/pull/2
logion-network/logion-internal#692
=> Upgrade pallet-logion-loc

Cargo.lock, node/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
* Add `pallet-logion-vote` to the runtime - see https://github.com/logion-network/logion-pallets/pull/5).
* Upgrade to `polkadot-v0.9.35`.
logion-network/logion-internal#713
=> Add pallet logion-vote; upgrade to polkadot-v0.9.35.

Cargo.lock, runtime/src/lib.rs
* Upgrade logion pallets and dependencies
* Set new limits
logion-network/logion-internal#764
=> Configure verified issuers and records

Cargo.lock, runtime/src/lib.rs
* Implement runtime api `FeesApi`.
* Configure Parameters for Storage Fees.
logion-network/logion-internal#830
=> Estimate File Storage Fees.

Cargo.lock, runtime/src/lib.rs
* Companion of https://github.com/logion-network/logion-pallets/pull/21
* Expose Legal Fees in Runtime API.
* chore: Remove old migration.
logion-network/logion-internal#893
=> Legal Fees for LOCs

Cargo.lock, runtime/src/lib.rs
* include items publication by requester/issuer;
* include acknowledgement of items by LLO.
Related PR's:
- https://github.com/logion-network/logion-pallets/pull/22
- https://github.com/logion-network/logion-pallets/pull/23
logion-network/logion-internal#897
=> Item publication by requester/issuer; Acknowledge by LLO

Cargo.lock, node/Cargo.toml, node/src/service.rs, runtime/Cargo.toml, runtime/src/lib.rs
* Companion of https://github.com/logion-network/logion-pallets/pull/27
logion-network/logion-internal#888
=> Upgrade to polkadot-v0.9.42

Cargo.lock, README.md, node/Cargo.toml, node/src/command.rs, runtime/Cargo.toml, runtime/src/lib.rs
* With https://github.com/logion-network/logion-pallets/pull/29, this enabled to test the `HashLocPublicData` migration on real data
https://github.com/logion-network/logion-internal/issues/928
=> Activate and document try-runtime

Cargo.lock, README.md, node/Cargo.toml, node/src/command.rs, runtime/Cargo.toml, runtime/src/lib.rs
* Companion of https://github.com/logion-network/logion-pallets/pull/28
* try-runtime is re-enabled and documented
logion-network/logion-internal#928
=> Store hashes of LOC public data

Cargo.lock, node/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
* Companion of https://github.com/logion-network/logion-pallets/pull/32
* Fixes storage versions for pallets assets, balances and grandpa (prevented try-runtime to run properly)
logion-network/logion-internal#949
=> Hash item and record items

Cargo.lock, runtime/src/lib.rs
* Companion of https://github.com/logion-network/logion-pallets/pull/33
logion-network/logion-internal#958
=> Enable value fees

Cargo.lock, runtime/src/lib.rs
* Companion of https://github.com/logion-network/logion-pallets/pull/35
logion-network/logion-internal#983
=> Enable custom legal fees

Cargo.lock, node/Cargo.toml, node/src/chain_spec.rs, node/src/command.rs, node/src/rpc.rs, node/src/service.rs, runtime/Cargo.toml, runtime/src/lib.rs
* Companion of https://github.com/logion-network/logion-pallets/pull/36
* :warning: To be merged only after sprint 60's release
logion-network/logion-internal#964
=> Upgrade to polkadot-v1.0.0

Cargo.lock, runtime/src/lib.rs
* Companion of https://github.com/logion-network/logion-pallets/pull/39
* Update dependencies.
logion-network/logion-internal#1028
=> Upgrade pallets (Batch close).

Cargo.lock, runtime/src/lib.rs
Companion of https://github.com/logion-network/logion-pallets/pull/41
logion-network/logion-internal#1051
=> Recurrent fees

Cargo.lock, runtime/src/lib.rs
* Companion of https://github.com/logion-network/logion-pallets/pull/43
* Validators are rewarded as if they were collators.
* Re-word comment explaining inflation details.
logion-network/logion-internal#1066
=> Validators remuneration

Cargo.lock, node/Cargo.toml, node/src/service.rs, runtime/Cargo.toml, runtime/src/lib.rs
* Upgrade to polkadot-v1.2.0.
* Remove past migration.
logion-network/logion-internal#1069
=> Upgrade to polkadot-v1.2.0

Cargo.lock, node/Cargo.toml, node/src/chain_spec.rs, runtime/Cargo.toml, runtime/src/lib.rs
Companion of https://github.com/logion-network/logion-pallets/pull/46
- Add required new types to `pallet-balances` config.
- Add required new types to `pallet-treasury` config.
- Remove `pallet-assets`.
logion-network/logion-internal#1080
=> Upgrade to polkadot-v1.3.0.
